/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import io.swagger.dto.PagoDTO;
import io.swagger.dto.PedidoDTO;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;
import java.util.ArrayList;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-11T02:16:01.140Z")

@Validated
@Api(value = "pedido", description = "the pedido API")
@RequestMapping(value = "/paolagutierz/BubbleCoffee/2.0.0")
public interface PedidoApi {

    @ApiOperation(value = "Obtener detalle del pedido pendiente por pagar", nickname = "pedidoDetallePedidoIdGet", notes = "detalle de pedido pagado.", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "pedido encontrado", response = PedidoDTO.class),
            @ApiResponse(code = 400, message = "entrada incorrecta"),
            @ApiResponse(code = 404, message = "pedido no encontrado") })
    @RequestMapping(value = "/pedido/detalle/{pedidoId}", produces = { "application/json" }, method = RequestMethod.GET)
    ResponseEntity<PedidoDTO> pedidoDetallePedidoIdGet(
            @ApiParam(value = "ver detalle de pedido para producirlo", required = true) @PathVariable("pedidoId") String pedidoId);

    @ApiOperation(value = "Pagar pedido", nickname = "PagoPost", notes = "obtener el pedido por Id para pagarlo", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Pedido pagado", response = PedidoDTO.class),
            @ApiResponse(code = 400, message = "entrada no valida"),
            @ApiResponse(code = 409, message = "pago duplicado") })
    @RequestMapping(value = "/pedido/pago/{pedidoId}", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.POST)
    ResponseEntity<PagoDTO> PagoPost(
            @ApiParam(value = "pedido id", required = true) @PathVariable("pedidoId") String pedidoId,
            @ApiParam(value = "pagar pedido") @Valid @RequestBody PagoDTO pagoDTO);

    @ApiOperation(value = "Cancelar pedido", nickname = "pedidoPedidoIdDelete", notes = "Cancelar pedido", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "pedido cancelado", response = PedidoDTO.class),
            @ApiResponse(code = 404, message = "no encontrado") })
    @RequestMapping(value = "/pedido/{pedidoId}", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.DELETE)
    ResponseEntity<PedidoDTO> pedidoPedidoIdDelete(
            @ApiParam(value = "pedido id", required = true) @PathVariable("pedidoId") String pedidoId);

    @ApiOperation(value = "Buscar pedido por ID", nickname = "pedidoPedidoIdGet", notes = "Obtener pedido por ID", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "ver pedido", response = PedidoDTO.class),
            @ApiResponse(code = 400, message = "id incorrecto"),
            @ApiResponse(code = 404, message = "pedido no encontrado") })
    @RequestMapping(value = "/pedido/{pedidoId}", produces = { "application/json" }, method = RequestMethod.GET)
    ResponseEntity<PedidoDTO> pedidoPedidoIdGet(
            @ApiParam(value = "buscar pedido por id", required = true) @PathVariable("pedidoId") String pedidoId);

    @ApiOperation(value = "Modificar pedido", nickname = "pedidoPedidoIdPut", notes = "Actualizar pedido", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "Pedido actualizado", response = PedidoDTO.class),
            @ApiResponse(code = 404, message = "Not Found"),
            @ApiResponse(code = 405, message = "Metodo no permitido") })
    @RequestMapping(value = "/pedido/{pedidoId}", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.PUT)
    ResponseEntity<PedidoDTO> pedidoPedidoIdPut(
            @ApiParam(value = "cambiar o actualizar pedido por id", required = true) @PathVariable("pedidoId") String pedidoId,
            @ApiParam(value = "pedido a actualizar") @Valid @RequestBody PedidoDTO pedido);

    @ApiOperation(value = "Generar pedido", nickname = "pedidoPost", notes = "Hacer pedido", response = PedidoDTO.class, tags = {
            "Pedido", })
    @ApiResponses(value = {
            @ApiResponse(code = 201, message = "pedido created", response = PedidoDTO.class),
            @ApiResponse(code = 400, message = "entrada no valida"),
            @ApiResponse(code = 409, message = "ya existe el pedido") })
    @RequestMapping(value = "/pedido", produces = { "application/json" }, consumes = {
            "application/json" }, method = RequestMethod.POST)
    ResponseEntity<PedidoDTO> pedidoPost(@ApiParam(value = "Agregar pedido") @Valid @RequestBody ArrayList<Integer> productos);

}
